resolver: lts-13.6
packages:
- .
extra-deps:
- git: https://github.com/nh2/linux-ptrace
  commit: a085a5c448389e44992d94079ac4eec852ff5e06
- git: git@github.com:GaloisInc/posix-waitpid.git
  commit: 291b970f2ec6f57e6c65dde2432d7bf198f307c3

allow-newer: true
