resolver: lts-13.6
packages:
- .
extra-deps:
- git: https://github.com/nh2/linux-ptrace
  commit: 1625f056bd79d24b8823b050f069c8b440240eda
- git: https://github.com/nh2/posix-waitpid.git
  commit: d2d7e06d85965dd022705d3d4e8348940afabb5f

allow-newer: true
