resolver: lts-13.6
packages:
- .
extra-deps:
- git: https://github.com/nh2/linux-ptrace
  commit: 2e36842a4b1cd152de210638df29a513937e4ce3
- git: https://github.com/nh2/posix-waitpid.git
  commit: cb4b4d23e5344ff0f5ee607ae9862c20ab612ebb

allow-newer: true
