resolver: lts-13.6
packages:
- .
extra-deps:
- git: https://github.com/nh2/linux-ptrace
  commit: 1625f056bd79d24b8823b050f069c8b440240eda
- git: https://github.com/nh2/posix-waitpid.git
  commit: cb4b4d23e5344ff0f5ee607ae9862c20ab612ebb

allow-newer: true
