version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - hatrace-{{ checksum "stack.yaml" }}-{{ checksum "hatrace.cabal" }}
            - hatrace-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --color never setup
      - run:
          name: Run tests
          command: stack --color never test
      - run:
          name: Install executable
          command: stack --color never install
      - save_cache:
          name: Cache Dependencies
          key: hatrace-{{ checksum "stack.yaml" }}-{{ checksum "hatrace.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/.local/bin/hatrace
          destination: hatrace
